Make landing categories great again (with the ability to configure)
WeareJH/m2-module-landing-categories pull request #3
Opened 2019-02-22 10:25 UTC by JamelleG

This adds the ability to configure different landing category pages using a custom config file `layout_categories.xml` which is read and then injected into the same functionality that the module currently uses but this makes it driven by config values instead of hardcoded. (which was not a requirement at the time but now it is so yeah)

2019-02-26 10:19 UTC, annybs submitted a review, later dismissed
LGTM 👌 Given that this has to do with https://github.com/WeareJH/trend-machinery/pull/51 I would recommend also tagging the appropriate version after merge. There's a reference to version 1.2.2 somewhere in your code, but check with the primary code owner of this module.

2019-02-27 15:55 UTC, dcabrejas requested changes

2019-02-27 15:55 UTC, dcabrejas commented on Plugin/Category/Attribute/Source/ModePlugin.php
>      const DM_LANDING = 'JH_LANDING';
Remove this constant. It's no longer being used.

2019-02-27 15:55 UTC, dcabrejas commented on Model/Widget/Instance.php
>      const LANDING_CATEGORY_LAYOUT_HANDLE = 'jh_category_landing';
Remove this constant. It's no longer used.

2019-02-27 15:55 UTC, dcabrejas commented on Model/Widget/Instance.php
> +        \Magento\Framework\Model\Context $context,
Could we import all those fully qualified names at the top of the file instead using `use` statements please?

2019-02-27 15:55 UTC, dcabrejas commented on Block/Adminhtml/Widget/Instance/Edit/Tab/Main/Layout.php
> +                'label' => 'Categories',
Can more than one category view type share the same label and code? Does this not create conflicts?

2019-02-27 15:55 UTC, dcabrejas commented on Block/Adminhtml/Widget/Instance/Edit/Tab/Main/Layout.php
> +        \Magento\Backend\Block\Template\Context $context,
Could we import this FQNs using `use` statements at the top of the file please?

2019-02-27 16:05 UTC, JamelleG commented on Block/Adminhtml/Widget/Instance/Edit/Tab/Main/Layout.php
> +                'label' => 'Categories',
In this case no because the code/label is applied to the group type instead of the specific view.
They also do the same for each product type (simple,configurable) all have the label 'Products'

2019-02-28 10:31 UTC, dcabrejas approved these changes

2019-02-28 10:32 UTC, dcabrejas commented
Hi @JamelleG Good work! Let's get this merged and tagged.

2019-02-28 10:32 UTC, merged